APPOINTMENT_STATUS_SCHEDULED = "scheduled"
APPOINTMENT_STATUS_CONFIRMED = "confirmed"
APPOINTMENT_STATUS_COMPLETED = "completed"
APPOINTMENT_STATUS_CANCELLED = "cancelled"
APPOINTMENT_STATUS_NO_SHOW = "no_show"
APPOINTMENT_STATUS_RESCHEDULED = "rescheduled"


BOOKING_CHANNEL_WEB = "web"
BOOKING_CHANNEL_ADMIN = "admin"
BOOKING_CHANNEL_WHATSAPP = "whatsapp"
BOOKING_CHANNEL_INSTAGRAM = "instagram"
BOOKING_CHANNEL_PHONE = "phone"
BOOKING_CHANNEL_AI = "ai"